version: "3.7"

services:
  api: &api
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    image: profmcdan/incubatorngapi
    command: gunicorn -w 4 core.wsgi -b 0.0.0.0:8000
    volumes:
      - ./app:/app
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - redis
      - db

  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - 5432:5432

  redis:
    image: redis:alpine

  celery:
    <<: *api
    command: celery worker --app=core --loglevel=info --logfile=logs/celery.log
    ports: []
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - api

  celery-beat:
    <<: *api
    command: celery -A core beat -l info
    ports: []
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - celery

  dashboard:
    <<: *api
    command: flower -A core --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5555:5555
    env_file:
      - ./.env
    depends_on:
      - api
      - redis
      - celery

  nginx-proxy:
    container_name: nginx-proxy
    build:
      context: .
      dockerfile: docker/prod/nginx/Dockerfile
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - api

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    env_file:
      - ./.env.staging.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
    depends_on:
      - nginx-proxy

  # nginx:
  #   build:
  #     context: .
  #     dockerfile: docker/prod/nginx/Dockerfile
  #   ports:
  #     - 1377:80
  #   depends_on:
  #     - api

volumes:
  postgres_data:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
